In [1]:
import numpy as np

In [2]:
my_arr = np.array([3,4,5])

In [3]:
my_arr[0]

3

In [4]:
my_arr.shape

(3,)

In [5]:
my_arr.dtype

dtype('int32')

In [6]:
my_arr[0] = 6

In [7]:
my_arr

array([6, 4, 5])

## Array Creations using Numpy

#### Using Python Objects (Lists, tuples & sets)

In [8]:
list_arr = np.array([[1,2,3], [5,8,5],[3,8,1]])

In [9]:
list_arr

array([[1, 2, 3],
       [5, 8, 5],
       [3, 8, 1]])

In [10]:
list_arr.dtype

dtype('int32')

In [11]:
list_arr.size

9

#### Numpy functions

In [12]:
zeros = np.zeros((2,5))

In [13]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
zeros.dtype

dtype('float64')

In [15]:
zeros.shape

(2, 5)

In [16]:
rng = np.arange(15)

In [17]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
lspace = np.linspace(1,5,12)

In [19]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [20]:
test_space = np.linspace(1,4,4)

In [21]:
test_space

array([1., 2., 3., 4.])

In [22]:
emp = np.empty((4,6))

In [23]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.89145198e-307, 3.33772113e-307, 1.89143501e-307],
       [1.42413555e-306, 1.78019082e-306, 1.37959740e-306,
        6.23057349e-307, 1.02360935e-306, 1.69120416e-306],
       [1.78022342e-306, 6.23058028e-307, 1.06811422e-306,
        9.45699680e-308, 1.11258854e-306, 1.11261502e-306],
       [1.42410839e-306, 7.56597770e-307, 6.23059726e-307,
        1.42419530e-306, 7.56602523e-307, 1.29061821e-306]])

In [24]:
emp_like = np.empty_like(lspace)

In [25]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [26]:
ide = np.identity(45)

In [27]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [28]:
arr = np.arange(99)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
arr = arr.reshape(3,33)

In [31]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
arr.shape

(3, 33)